version: '3.1'
services:
  web:
    image: odoo:17.0
    depends_on: []
    ports:
      - "8069:8069"
    environment:
    - HOST=postgres-db-1
    - USER=odoo
    - PASSWORD=1234
    networks:
      red-local-docker:
        ipv4_address: 172.20.0.11

networks:
  red-local-docker:
    external: true