version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234      #sfuKTJGExBqRTpPJXubX
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      red-local-docker:
        ipv4_address: 172.20.0.2

volumes:
  db:
    driver: local

networks:
  red-local-docker:
    external: true

