version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      red-local-docker:
        ipv4_address: 172.20.0.4
    ports:
      - '27017:27017'

networks:
  red-local-docker:
    external: true    