version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - "6379:6379"
    volumes:
      - /redis/d–∞ta:/root/redis
      - /redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      red-local-docker:
        ipv4_address: 172.20.0.5

volumes:
  db:
    driver: local

networks:
  red-local-docker:
    external: true